[package]
name = "algs"
version = "0.1.0"
authors = ["saebs <ntabenism@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
member = ["aplusb"]

[dependencies]
